---
- name: Check if Docker is already present.
  ansible.builtin.command: which docker
  failed_when: false
  changed_when: false
  check_mode: false
  register: docker_command_result

- name: Download Docker install convenience script.
  ansible.builtin.get_url:
    url: https://get.docker.com/
    dest: /tmp/get-docker.sh
    mode: 0775
  when: docker_command_result.rc == 1

- name: Run Docker install convenience script.
  ansible.builtin.command: /tmp/get-docker.sh
  environment:
    CHANNEL: stable
  when: docker_command_result.rc == 1

- name: Ensure Docker is started.
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Build dependency list (Debian).
  ansible.builtin.set_fact:
    docker_debian_dependencies: >-
      {{ ['libffi-dev', 'libssl-dev', 'python3-dev', 'python3-pip', 'git', 'rsync', 'resolvconf']
         + ((docker_install_compose_plugin | default(true) | bool)
            | ternary(['docker-compose-plugin'], [])) }}
  when: ansible_facts.os_family == "Debian"

- name: Ensure dependencies are installed (Debian).
  ansible.builtin.apt:
    name: "{{ docker_debian_dependencies }}"
    state: present
  when: ansible_facts.os_family == "Debian"

- name: Build dependency list (Archlinux).
  ansible.builtin.set_fact:
    docker_arch_dependencies: >-
      {{ ['libffi', 'openssl', 'base-devel', 'python-pip', 'git', 'rsync']
         + ((docker_install_compose_plugin | default(true) | bool)
            | ternary(['docker-compose-plugin'], [])) }}
  when: ansible_facts.os_family == "Archlinux"

- name: Ensure dependencies are installed (Archlinux).
  community.general.pacman:
    name: "{{ docker_arch_dependencies }}"
    state: present
  when: ansible_facts.os_family == "Archlinux"

- name: "Ensure user is added to the docker group: {{ ansible_user }}"
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

# reset_connection doesn't support conditionals.
- name: Reset connection so docker group is picked up.
  meta: reset_connection
