version: "3.8"

volumes:
  promagent_data:

services:
  ping:
    image: prom/blackbox-exporter:latest
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./blackbox/config:/config
    ports:
      - "9115:9115"
    command:
      - "--config.file=/config/blackbox.yml"

  fasttest:
    build:
      context: ./exporters/fast
    restart: always
    network_mode: host
    environment:
      - FAST_EXPORTER_PORT=9801
      - FAST_EXPORTER_TIMEOUT=180
      - FAST_EXPORTER_SAMPLE_TTL=600
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://0.0.0.0:9801/metrics"]
      interval: 10m
      timeout: 15s
      retries: 1

  nodeexp:
    image: prom/node-exporter:latest
    restart: always
    privileged: true
    pid: host
    network_mode: host
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro

  promagent:
    image: prom/prometheus:latest
    restart: always
    network_mode: host
    user: "0"
    command:
      - "--config.file=/etc/prom-agent/prometheus.yml"
      - "--storage.tsdb.path=/prometheus-agent"
      - "--storage.tsdb.retention.time=14d"
    volumes:
      - ./prometheus-agent/:/etc/prom-agent/:ro
      - promagent_data:/prometheus-agent
