version: "3.8"

services:
  ping:
    image: prom/blackbox-exporter:latest
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./blackbox/config:/config
    ports:
      - "9115:9115"
    command:
      - "--config.file=/config/blackbox.yml"

  speedtest:
    image: miguelndecarvalho/speedtest-exporter:latest
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://0.0.0.0:9798/"]
      timeout: 10s
    ports:
      - "9798:9798"

  nodeexp:
    image: prom/node-exporter:latest
    restart: always
    privileged: true
    pid: host
    network_mode: host
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
